GET http://localhost:8080/film/20
Accept: application/json

###
GET http://localhost:8080/film/debut/20
Accept: application/json

###
GET http://localhost:8080/film/lastrental/20
Accept: application/json

###
GET http://localhost:8080/film/maxrental/20
Accept: application/json

###
GET http://localhost:8080/film/findByParameters?title=mod&actor=zero_cage
Accept: application/json

###
POST http://localhost:8080/film/rental/addFilm/21

###
GET http://localhost:8080/film/rental
Accept: application/json

###
DELETE http://localhost:8080/film/rental/deleteFilm/938

###
POST http://localhost:8080/customer/addAddress
Content-Type: application/json

{  
  "address": "add",
  "address2": "add2",
  "district": "dis",
  "city": "Aden",
  "postal_code": 1234,
  "phone": 777643534556
}

###
POST http://localhost:8080/customer/addCustomer
Content-Type: application/json

{
  "store_id": 1,
  "first_name": "user",
  "last_name": "test",
  "email": "test@gmail.com",
  "address_id": 609,
  "active": 1,
  "create_date": "2021-11-24T22:25:53.378Z"
}

###
GET http://localhost:8080/costumer/payment/address/12
Accept: application/json

###
PUT http://localhost:8080/costumer/payment/address
Content-Type: application/json

{
  "address_id": 16,
  "address": "808 Bhopal Manor",
  "address2": "",
  "district": "Haryana",
  "city": "Yamuna Nagar",
  "postal_code": 10673,
  "phone": 465887807014
}

###
GET http://localhost:8080/costumer/payment/email/12


###
POST http://localhost:8080/costumer/payment/12
Content-Type:  application/json

{
  "store_id": 1,
  "rentalFilm":  [
    {
      "filmId": 11,
      "title": "ALAMO VIDEOTAPE",
      "description": "A Boring Epistle of a Butler And a Cat who must Fight a Pastry Chef in A MySQL Convention",
      "releaseYear": 2006,
      "rental_duration": 6,
      "rental_rate": 0.99,
      "lastUpdate": "2006-02-15T04:00:00.000+00:00"
    },
    {
      "filmId": 21,
      "title": "AMERICAN CIRCUS",
      "description": "A Insightful Drama of a Girl And a Astronaut who must Face a Database Administrator in A Shark Tank",
      "releaseYear": 2006,
      "rental_duration": 3,
      "rental_rate": 4.99,
      "lastUpdate": "2006-02-15T04:00:00.000+00:00"
    }
  ],
  "rental_date": "2021-11-25T22:25:53.378Z",
  "payment_date": "2021-11-25T22:25:53.378Z",
  "return_date": "2021-11-28T22:25:53.378Z",
  "discount": 0.15,
  "total": 15.249
}

###
GET http://localhost:8080/costumer/MARY.SMITH@sakilacustomer.org
Accept: application/json

###
GET http://localhost:8080/costumer/city/20
Accept: application/json